import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:go_router/go_router.dart';
import 'package:material_ui/material_ui.dart';
import 'package:mobile_app_starter/bloc/favorites/favorites_bloc.dart';
import 'package:mobile_app_starter/bloc/search/search_bloc.dart';
import 'package:mobile_app_starter/cubit/pokemon_cubit.dart';
import 'package:mobile_app_starter/l10n/app_localizations.dart';
import 'package:mobile_app_starter/repository/pokemon_repository.dart';
import 'package:mobile_app_starter/router/routes.dart';

import '../helpers/pump_app.dart';

void main() {
  group('app routes', () {
    testWidgets('build MaterialPage, not NoTransitionPage', (
      WidgetTester tester,
    ) async {
      // Guards a silent failure: without MaterialPageRouteData go_router falls
      // back to NoTransitionPage and every page transition disappears, with no
      // error or log. Confirmed to fail with the mixin removed.
      final GoRouter router = GoRouter(routes: $appRoutes);
      addTearDown(router.dispose);

      await tester.pumpWidget(
        RepositoryProvider<PokemonRepository>.value(
          value: MockPokemonRepository(),
          child: MultiBlocProvider(
            providers: <BlocProvider<dynamic>>[
              BlocProvider<PokemonCubit>.value(value: buildMockPokemonCubit()),
              BlocProvider<SearchBloc>.value(value: buildMockSearchBloc()),
              BlocProvider<FavoritesBloc>.value(
                value: buildMockFavoritesBloc(),
              ),
            ],
            child: MaterialApp.router(
              routerConfig: router,
              localizationsDelegates: AppLocalizations.localizationsDelegates,
              supportedLocales: AppLocalizations.supportedLocales,
            ),
          ),
        ),
      );
      await tester.pump();

      final Navigator navigator = tester.widget<Navigator>(
        find.byType(Navigator).last,
      );

      expect(navigator.pages, isNotEmpty);
      for (final Page<dynamic> page in navigator.pages) {
        expect(
          page,
          isA<MaterialPage<void>>(),
          reason:
              'Route built a ${page.runtimeType}. Every typed route in '
              'lib/router/routes.dart must mix in MaterialPageRouteData.',
        );
      }
    });

    test('the detail route builds a type-safe location', () {
      // Generated by go_router_builder; fails if `path:` in routes.dart moves.
      expect(const PokemonDetailPage(id: 25).location, '/pokemon/25');
    });
  });
}
